### ISSUE TITLE
use-v-on-exact example would not trigger

### ISSUE THREAD

**Issue by Shinigami92** [TokugawaTakeshi/vue-eslint-pug_support_test#2]
https://github.com/TokugawaTakeshi/vue-eslint-pug_support_test/blob/8bf2455c2095c17c2a26e0ff7080fa49c7d25812/src/App.vue#L38

This is one of the next rules I would tackle, but I looked into your example and this would currently never trigger

Update it and maybe re-read the rule description: https://eslint.vuejs.org/rules/use-v-on-exact.html#rule-details

**Comment by TokugawaTakeshi** [comment]
I updated this violation and now it is exactly as in documentation, just in Pug syntax.
Please approve my PR if this issue solved.

https://github.com/TokugawaTakeshi/vue-eslint-pug_support_test/pull/5
