### ISSUE TITLE
Invalid Vue 3 pug content

### ISSUE THREAD

**Issue by Shinigami92** [TokugawaTakeshi/vue-eslint-pug_support_test#6]
https://github.com/TokugawaTakeshi/vue-eslint-pug_support_test/blob/537e9e6814c8951853ec5373b94faf01108b8347/Vue3/src/App.vue#L76

This line breaks the whole linting / parsing of pug content from the file

Comment it out and you instantly see that linter successfully triggers

**Comment by TokugawaTakeshi** [comment]
Just make commit fixing this issue.

As far as I knew from the "Compilers: Principles, Techniques, & Tools", lexers/parsers must be tolerant to any kind of errors. 
If there is some hard error in code, one of strategy is search of the next valid token and then continue the parsing. The braking of the whole linting/parsing makes the effect that no errors are present, thus this deffect must be fixed.

Well, I'm understand that the are a lot of other important tasks left. Just please, add this issue to your project.

**Comment by Shinigami92** [comment]
I assume this 
should be done in https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc/issues/12
+++++++++++++++++++++++++++++++++
